# Generated by Django 5.0 on 2023-12-30 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labor', '0002_labor_register_otp'),
        ('master', '0002_base_table_remove_counter_table_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='parties_detail',
            fields=[
                ('base_table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.base_table')),
                ('firm_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
            ],
            bases=('master.base_table',),
        ),
    ]
