# Generated by Django 5.0 on 2024-01-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_counter_table_last_task_id'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('base_table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='master.base_table')),
                ('task_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('total_payment', models.FloatField()),
                ('task_status', models.CharField(blank=True, choices=[('Pending', 'Task Pending'), ('Ongoing', 'Task On-Going'), ('Done', 'Task Done')], default='Pending', max_length=50)),
                ('paid_payment', models.FloatField(blank=True, default=0)),
                ('payment_status', models.CharField(blank=True, choices=[('Pending', 'Payment Pending'), ('Done', 'Payment Done'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.parties_detail')),
            ],
            bases=('master.base_table',),
        ),
    ]
