# Generated by Django 5.0 on 2024-01-07 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_labor_register_otp'),
        ('master', '0003_counter_table_last_task_id'),
        ('parties', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labor_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register'),
        ),
        migrations.AddField(
            model_name='task',
            name='remaining_payment',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='payment_installment',
            fields=[
                ('base_table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='master.base_table')),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('payment_entry', models.FloatField(default=0)),
                ('paid_date', models.DateTimeField(default=datetime.date(2024, 1, 7))),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.labor_register')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.task')),
            ],
            bases=('master.base_table',),
        ),
    ]
