# Generated by Django 5.0 on 2024-01-07 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_task_labor_id_alter_task_remaining_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
