# Generated by Django 5.0 on 2024-01-10 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_alter_payment_installment_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.date(2024, 1, 10)),
        ),
    ]
