# Generated by Django 5.0 on 2024-01-12 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_alter_payment_installment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_installment',
            name='base_table_ptr',
        ),
        migrations.AlterField(
            model_name='payment_installment',
            name='paid_date',
            field=models.DateField(default=datetime.date(2024, 1, 12)),
        ),
    ]
