# Generated by Django 5.0 on 2024-01-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_counter_table_last_payment_entry_id'),
        ('parties', '0009_remove_payment_installment_base_table_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_installment',
            name='base_table_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='master.base_table'),
            preserve_default=False,
        ),
    ]
