# Generated by Django 5.0 on 2023-12-16 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='counter_table',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='counter_table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='counter_table',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='counter_table',
            name='base_table_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.base_table'),
            preserve_default=False,
        ),
    ]
