# Generated by Django 5.0 on 2024-01-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_base_table_remove_counter_table_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_table',
            name='last_task_id',
            field=models.IntegerField(default=0),
        ),
    ]
