# Generated by Django 5.0 on 2024-01-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_counter_table_last_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter_table',
            name='last_payment_entry_id',
            field=models.IntegerField(default=0),
        ),
    ]
