# Generated by Django 5.0 on 2023-12-18 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_base_table_remove_counter_table_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='labor_register',
            fields=[
                ('base_table_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='master.base_table')),
                ('labor_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('credential_is_sent', models.BooleanField(default=False)),
            ],
            bases=('master.base_table',),
        ),
    ]
